# Configuration and constants.

DEFAULT_SUMMON_PREFIX = "~!"
DEFAULT_HELP_KEY = "help"
MAX_MESSAGE_LENGTH = 1900
MAX_COMMAND_WORKERS = 5
COMMAND_TIMEOUT = 10.0  # in seconds
INVISIBLE_SPACE = '\u200b'
IGNORE_STRIKETHROUGH = True
IGNORE_UNRECOGNIZED = True
